[theme]
primaryColor = "#1E90FF"  # Blue background color
backgroundColor = "#1E90FF"  # Blue background color
secondaryBackgroundColor = "#1E90FF"  # Blue background color
textColor = "#FFFFFF"  # White text color
font = "sans-serif"  # Specify the desired font if needed
